[build-system]
requires = [
    "setuptools >= 61.0",

]
build-backend = "setuptools.build_meta"

[project]
name = "verschneidungstool"
license = {text = "GPL-2.0 AND BSD-3-Clause"}
dynamic = ["version"]

dependencies = [
    'psycopg2',
    'lxml',
    'openpyxl',
    'sqlalchemy',
]

authors = [
    {name = "Christoph Franke", email = "franke@ggr-planung.de"},
    {name = "Max Bohnet", email = "bohnet@ggr-planung.de"},
]

description = "graphical user interface for computing intersections on travel analysis zone"
maintainers = [
    { name = "Max Bohnet", email = "bohnet@ggr-planung.de" },
]
requires-python = ">=3.10"

[tool.setuptools.dynamic]
version = {attr = "verschneidungstool.__version__"}

[tool.setuptools.package-data]
'verschneidungstool' = ['dlls/*', 'docs/*']

[project.scripts]
verschneidungstool = "verschneidungstool.main:startmain"

[project.urls]
Repository = "https://github.com/MaxBo/verschneidungstool"