# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(550, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QtCore.QSize(550, 250))
        Settings.setMaximumSize(QtCore.QSize(550, 300))
        Settings.setSizeGripEnabled(False)
        Settings.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_config_button = QtWidgets.QPushButton(Settings)
        self.load_config_button.setObjectName("load_config_button")
        self.horizontalLayout.addWidget(self.load_config_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OK_button = QtWidgets.QPushButton(Settings)
        self.OK_button.setObjectName("OK_button")
        self.horizontalLayout.addWidget(self.OK_button)
        self.cancel_button = QtWidgets.QPushButton(Settings)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.dblogin_tab = QtWidgets.QWidget()
        self.dblogin_tab.setObjectName("dblogin_tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.dblogin_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 491, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.username_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.username_edit.setObjectName("username_edit")
        self.gridLayout_3.addWidget(self.username_edit, 0, 2, 1, 4)
        self.password_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.gridLayout_3.addWidget(self.password_edit, 1, 2, 1, 4)
        self.srid_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.srid_edit.setObjectName("srid_edit")
        self.gridLayout_3.addWidget(self.srid_edit, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 6, 0, 1, 1)
        self.srid_default_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.srid_default_button.setObjectName("srid_default_button")
        self.gridLayout_3.addWidget(self.srid_default_button, 6, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 1)
        self.port_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.port_edit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.port_edit.setObjectName("port_edit")
        self.gridLayout_3.addWidget(self.port_edit, 3, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem2, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 4, 1, 1)
        self.host_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.host_edit.setObjectName("host_edit")
        self.gridLayout_3.addWidget(self.host_edit, 3, 2, 1, 2)
        self.dbname_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.dbname_edit.setObjectName("dbname_edit")
        self.gridLayout_3.addWidget(self.dbname_edit, 4, 2, 1, 2)
        self.tabWidget.addTab(self.dblogin_tab, "")
        self.env_tab = QtWidgets.QWidget()
        self.env_tab.setObjectName("env_tab")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.env_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 491, 128))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.psql_browse_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.psql_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.psql_browse_button.setObjectName("psql_browse_button")
        self.gridLayout_4.addWidget(self.psql_browse_button, 0, 3, 1, 1)
        self.shp2pgsql_browse_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.shp2pgsql_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.shp2pgsql_browse_button.setObjectName("shp2pgsql_browse_button")
        self.gridLayout_4.addWidget(self.shp2pgsql_browse_button, 1, 3, 1, 1)
        self.shp2pgsql_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.shp2pgsql_edit.setObjectName("shp2pgsql_edit")
        self.gridLayout_4.addWidget(self.shp2pgsql_edit, 1, 1, 1, 1)
        self.psql_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.psql_edit.setObjectName("psql_edit")
        self.gridLayout_4.addWidget(self.psql_edit, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 3, 0, 1, 1)
        self.pgsql2shp_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.pgsql2shp_edit.setObjectName("pgsql2shp_edit")
        self.gridLayout_4.addWidget(self.pgsql2shp_edit, 3, 1, 1, 1)
        self.pgsql2shp_browse_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pgsql2shp_browse_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pgsql2shp_browse_button.setObjectName("pgsql2shp_browse_button")
        self.gridLayout_4.addWidget(self.pgsql2shp_browse_button, 3, 3, 1, 1)
        self.tabWidget.addTab(self.env_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Einstellungen"))
        self.load_config_button.setText(_translate("Settings", "Konfiguration laden"))
        self.OK_button.setText(_translate("Settings", "OK"))
        self.cancel_button.setText(_translate("Settings", "Abbrechen"))
        self.label_5.setText(_translate("Settings", "Passwort"))
        self.label.setText(_translate("Settings", "DB-Projektion (SRID)"))
        self.srid_default_button.setText(_translate("Settings", "Default"))
        self.label_8.setText(_translate("Settings", "Datenbankname"))
        self.label_3.setText(_translate("Settings", "Username"))
        self.label_7.setText(_translate("Settings", "Host"))
        self.label_9.setText(_translate("Settings", "Port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dblogin_tab), _translate("Settings", "Datenbankverbindung"))
        self.label_6.setText(_translate("Settings", "psql.exe"))
        self.label_10.setText(_translate("Settings", "shp2pgsql.exe"))
        self.psql_browse_button.setText(_translate("Settings", "..."))
        self.shp2pgsql_browse_button.setText(_translate("Settings", "..."))
        self.label_11.setText(_translate("Settings", "pgsql2shp.exe"))
        self.pgsql2shp_browse_button.setText(_translate("Settings", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.env_tab), _translate("Settings", "Pfade"))

